# Compress with ouch
[[mgr.prepend_keymap]]
on = [ "C" ]
run = "plugin ouch"
desc = "Compress with ouch"

# Mount
# Select device to mount and jump to its mount point
[[mgr.prepend_keymap]]
on = [ "M", "m" ]
run = "plugin gvfs -- select-then-mount --jump"
desc = "Select device to mount and jump to its mount point"

# Remount device under current working directory
[[mgr.prepend_keymap]]
on = [ "M", "R" ]
run = "plugin gvfs -- remount-current-cwd-device"
desc = "Remount device under cwd"

# Select device then eject
[[mgr.prepend_keymap]]
on = [ "M", "u" ]
run = "plugin gvfs -- select-then-unmount --eject"
desc = "Select device then eject"

# Select device then force to eject/unmount
[[mgr.prepend_keymap]]
on = [ "M", "U" ]
run = "plugin gvfs -- select-then-unmount --eject --force"
desc = "Select device then force to eject/unmount"

# Add GVFS mount URI
[[mgr.prepend_keymap]]
on = [ "M", "a" ]
run = "plugin gvfs -- add-mount"
desc = "Add a GVFS mount URI"

# Edit GVFS mount URI
[[mgr.prepend_keymap]]
on = [ "M", "e" ]
run = "plugin gvfs -- edit-mount"
desc = "Edit a GVFS mount URI"

# Remove GVFS mount URI
[[mgr.prepend_keymap]]
on = [ "M", "r" ]
run = "plugin gvfs -- remove-mount"
desc = "Remove a GVFS mount URI"

# Jump to device mount point
[[mgr.prepend_keymap]]
on = [ "g", "m" ]
run = "plugin gvfs -- jump-to-device --automount"
desc = "Automount then select device to jump to its mount point"

# Jump back to previous cwd
[[mgr.prepend_keymap]]
on = [ "`", "`" ]
run = "plugin gvfs -- jump-back-prev-cwd"
desc = "Jump back to the position before jumped to device"

# Enable automount when cd
[[mgr.prepend_keymap]]
on = [ "M", "t" ]
run = "plugin gvfs -- automount-when-cd"
desc = "Enable automount when cd to device under cwd"

# Disable automount when cd
[[mgr.prepend_keymap]]
on = [ "M", "T" ]
run = "plugin gvfs -- automount-when-cd --disabled"
desc = "Disable automount when cd to device under cwd"

# SSHFS menu
[[mgr.prepend_keymap]]
on = [ "M", "s" ]
run = "plugin sshfs -- menu"
desc = "Open SSHFS options"

# Lazygit integration
[[mgr.prepend_keymap]]
on = [ "g", "i" ]
run = "plugin lazygit"
desc = "Run lazygit"

# Move in relative steps (examples)
[[mgr.prepend_keymap]]
on = [ "1" ]
run = "plugin relative-motions 1"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "2" ]
run = "plugin relative-motions 2"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "3" ]
run = "plugin relative-motions 3"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "4" ]
run = "plugin relative-motions 4"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "5" ]
run = "plugin relative-motions 5"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "6" ]
run = "plugin relative-motions 6"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "7" ]
run = "plugin relative-motions 7"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "8" ]
run = "plugin relative-motions 8"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "9" ]
run = "plugin relative-motions 9"
desc = "Move in relative steps"
